language: php
php:
  - '7.0'
  - '7.1'

# faster builds on new travis setup not using sudo
sudo: false

# cache composer cache
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin"
  - travis_retry composer install --no-interaction --prefer-dist --no-dev